openapi: 3.1.0
info:
  title: backup-gateway
  description: >-
    <p><fullname>Backup gateway</fullname> <p>Backup gateway connects Backup to
    your hypervisor, so you can create, store, and restore backups of your
    virtual machines (VMs) anywhere, whether on-premises or in the VMware Cloud
    (VMC) on Amazon Web Services.</p> <p>Add on-premises resources by connecting
    to a hypervisor through a gateway. Backup will automatically discover the
    resources in your hypervisor.</p> <p>Use Backup to assign virtual or
    on-premises resources to a backup plan, or run on-demand backups. Once you
    have backed up your resources, you can view them and restore them like any
    resource supported by Backup.</p> <p>To download the Amazon Web Services
    software to get started, navigate to the Backup console, choose
    <b>Gateways</b>, then choose <b>Create gateway</b>.</p></p>
paths:
  /:
    POST:
      summary: UpdateHypervisor
      description: >-
        <p>Updates a hypervisor metadata, including its host, username, and
        password. Specify which hypervisor to update using the Amazon Resource
        Name (ARN) of the hypervisor in your request.</p>
tags: []
