openapi: 3.1.0
info:
  title: chime-sdk-meetings
paths:
  /meetings/{MeetingId}/attendees?operation=batch-create:
    POST:
      summary: BatchCreateAttendee
      description: >-
        <p>Creates up to 100 attendees for an active Amazon Chime SDK meeting.
        For more information about the Amazon Chime SDK, see <a
        href="https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html">Using
        the Amazon Chime SDK</a> in the <i>Amazon Chime Developer Guide</i>.</p>
      tags:
        - Batches
        - Create
        - Attendees
        - Meetings
        - Identifiers
        - Attendees
        - Create
  /meetings/{MeetingId}/attendees/capabilities?operation=batch-update-except:
    PUT:
      summary: BatchUpdateAttendeeCapabilitiesExcept
      description: >-
        <p>Updates <code>AttendeeCapabilities</code> except the capabilities
        listed in an <code>ExcludedAttendeeIds</code> table.</p> <note> <p>You
        use the capabilities with a set of values that control what the
        capabilities can do, such as <code>SendReceive</code> data. For more
        information about those values, see .</p> </note> <p>When using
        capabilities, be aware of these corner cases:</p> <ul> <li> <p>If you
        specify <code>MeetingFeatures:Video:MaxResolution:None</code> when you
        create a meeting, all API requests that include
        <code>SendReceive</code>, <code>Send</code>, or <code>Receive</code> for
        <code>AttendeeCapabilities:Video</code> will be rejected with
        <code>ValidationError 400</code>.</p> </li> <li> <p>If you specify
        <code>MeetingFeatures:Content:MaxResolution:None</code> when you create
        a meeting, all API requests that include <code>SendReceive</code>,
        <code>Send</code>, or <code>Receive</code> for
        <code>AttendeeCapabilities:Content</code> will be rejected with
        <code>ValidationError 400</code>.</p> </li> <li> <p>You can't set
        <code>content</code> capabilities to <code>SendReceive</code> or
        <code>Receive</code> unless you also set <code>video</code> capabilities
        to <code>SendReceive</code> or <code>Receive</code>. If you don't set
        the <code>video</code> capability to receive, the response will contain
        an HTTP 400 Bad Request status code. However, you can set your
        <code>video</code> capability to receive and you set your
        <code>content</code> capability to not receive.</p> </li> <li> <p>When
        you change an <code>audio</code> capability from <code>None</code> or
        <code>Receive</code> to <code>Send</code> or <code>SendReceive</code> ,
        and if the attendee left their microphone unmuted, audio will flow from
        the attendee to the other meeting participants.</p> </li> <li> <p>When
        you change a <code>video</code> or <code>content</code> capability from
        <code>None</code> or <code>Receive</code> to <code>Send</code> or
        <code>SendReceive</code> , and if the attendee turned on their video or
        content streams, remote attendees can receive those streams, but only
        after media renegotiation between the client and the Amazon Chime
        back-end server.</p> </li> </ul>
      tags:
        - Batches
        - Update
        - Attendees
        - Capabilities
        - Except
        - Meetings
        - Identifiers
        - Attendees
        - Create
        - Attendees
        - Capabilities
        - Update
        - Except
  /meetings/{MeetingId}/attendees:
    GET:
      summary: ListAttendees
      description: >-
        <p> Lists the attendees for the specified Amazon Chime SDK meeting. For
        more information about the Amazon Chime SDK, see <a
        href="https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html">Using
        the Amazon Chime SDK</a> in the <i>Amazon Chime Developer Guide</i>.
        </p>
      tags:
        - Lists
        - Attendees
        - Meetings
        - Identifiers
        - Attendees
        - Create
        - Attendees
        - Capabilities
        - Update
        - Except
  /meetings:
    POST:
      summary: CreateMeeting
      description: >-
        <p>Creates a new Amazon Chime SDK meeting in the specified media Region
        with no initial attendees. For more information about specifying media
        Regions, see <a
        href="https://docs.aws.amazon.com/chime/latest/dg/chime-sdk-meetings-regions.html">Amazon
        Chime SDK Media Regions</a> in the <i>Amazon Chime Developer Guide</i>.
        For more information about the Amazon Chime SDK, see <a
        href="https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html">Using
        the Amazon Chime SDK</a> in the <i>Amazon Chime Developer Guide</i>.
        </p>
      tags:
        - Create
        - Meetings
        - Meetings
        - Identifiers
        - Attendees
        - Create
        - Attendees
        - Capabilities
        - Update
        - Except
        - Meetings
  /meetings?operation=create-attendees:
    POST:
      summary: CreateMeetingWithAttendees
      description: >-
        <p> Creates a new Amazon Chime SDK meeting in the specified media
        Region, with attendees. For more information about specifying media
        Regions, see <a
        href="https://docs.aws.amazon.com/chime/latest/dg/chime-sdk-meetings-regions.html">Amazon
        Chime SDK Media Regions</a> in the <i>Amazon Chime Developer Guide</i>.
        For more information about the Amazon Chime SDK, see <a
        href="https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html">Using
        the Amazon Chime SDK</a> in the <i>Amazon Chime Developer Guide</i>.
        </p>
      tags:
        - Create
        - Meetings
        - null
        - Attendees
        - Meetings
        - Identifiers
        - Attendees
        - Create
        - Attendees
        - Capabilities
        - Update
        - Except
        - Meetings
        - Meetings
  /meetings/{MeetingId}/attendees/{AttendeeId}:
    GET:
      summary: GetAttendee
      description: >-
        <p> Gets the Amazon Chime SDK attendee details for a specified meeting
        ID and attendee ID. For more information about the Amazon Chime SDK, see
        <a
        href="https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html">Using
        the Amazon Chime SDK</a> in the <i>Amazon Chime Developer Guide</i>.
        </p>
      tags:
        - Get
        - Attendees
        - Meetings
        - Identifiers
        - Attendees
        - Create
        - Attendees
        - Capabilities
        - Update
        - Except
        - Meetings
        - Meetings
        - Attendees
  /meetings/{MeetingId}:
    GET:
      summary: GetMeeting
      description: >-
        <p>Gets the Amazon Chime SDK meeting details for the specified meeting
        ID. For more information about the Amazon Chime SDK, see <a
        href="https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html">Using
        the Amazon Chime SDK</a> in the <i>Amazon Chime Developer Guide</i>.</p>
      tags:
        - Get
        - Meetings
        - Meetings
        - Identifiers
        - Attendees
        - Create
        - Attendees
        - Capabilities
        - Update
        - Except
        - Meetings
        - Meetings
        - Attendees
  /tags:
    GET:
      summary: ListTagsForResource
      description: <p>Returns a list of the tags available for the specified resource.</p>
      tags:
        - Lists
        - Tags
        - For
        - Resources
        - Meetings
        - Identifiers
        - Attendees
        - Create
        - Attendees
        - Capabilities
        - Update
        - Except
        - Meetings
        - Meetings
        - Attendees
        - Tags
  /meetings/{MeetingId}/transcription?operation=start:
    POST:
      summary: StartMeetingTranscription
      description: >-
        <p>Starts transcription for the specified <code>meetingId</code>. For
        more information, refer to <a
        href="https://docs.aws.amazon.com/chime-sdk/latest/dg/meeting-transcription.html">
        Using Amazon Chime SDK live transcription </a> in the <i>Amazon Chime
        SDK Developer Guide</i>.</p> <p>If you specify an invalid configuration,
        a <code>TranscriptFailed</code> event will be sent with the contents of
        the <code>BadRequestException</code> generated by Amazon Transcribe. For
        more information on each parameter and which combinations are valid,
        refer to the <a
        href="https://docs.aws.amazon.com/transcribe/latest/APIReference/API_streaming_StartStreamTranscription.html">StartStreamTranscription</a>
        API in the <i>Amazon Transcribe Developer Guide</i>.</p> <note> <p>By
        default, Amazon Transcribe may use and store audio content processed by
        the service to develop and improve Amazon Web Services AI/ML services as
        further described in section 50 of the <a
        href="https://aws.amazon.com/service-terms/">Amazon Web Services Service
        Terms</a>. Using Amazon Transcribe may be subject to federal and state
        laws or regulations regarding the recording or interception of
        electronic communications. It is your and your end users’ responsibility
        to comply with all applicable laws regarding the recording, including
        properly notifying all participants in a recorded session or
        communication that the session or communication is being recorded, and
        obtaining all necessary consents. You can opt out from Amazon Web
        Services using audio content to develop and improve AWS AI/ML services
        by configuring an AI services opt out policy using Amazon Web Services
        Organizations.</p> </note>
      tags:
        - Start
        - Meetings
        - Transcriptions
        - Meetings
        - Identifiers
        - Attendees
        - Create
        - Attendees
        - Capabilities
        - Update
        - Except
        - Meetings
        - Meetings
        - Attendees
        - Tags
        - Transcriptions
  /meetings/{MeetingId}/transcription?operation=stop:
    POST:
      summary: StopMeetingTranscription
      description: >-
        <p>Stops transcription for the specified <code>meetingId</code>. For
        more information, refer to <a
        href="https://docs.aws.amazon.com/chime-sdk/latest/dg/meeting-transcription.html">
        Using Amazon Chime SDK live transcription </a> in the <i>Amazon Chime
        SDK Developer Guide</i>.</p> <important> <p>By default, Amazon
        Transcribe may use and store audio content processed by the service to
        develop and improve Amazon Web Services AI/ML services as further
        described in section 50 of the <a
        href="https://aws.amazon.com/service-terms/">Amazon Web Services Service
        Terms</a>. Using Amazon Transcribe may be subject to federal and state
        laws or regulations regarding the recording or interception of
        electronic communications. It is your and your end users’ responsibility
        to comply with all applicable laws regarding the recording, including
        properly notifying all participants in a recorded session or
        communication that the session or communication is being recorded, and
        obtaining all necessary consents. You can opt out from Amazon Web
        Services using audio content to develop and improve Amazon Web Services
        AI/ML services by configuring an AI services opt out policy using Amazon
        Web Services Organizations.</p> </important>
      tags:
        - Stop
        - Meetings
        - Transcriptions
        - Meetings
        - Identifiers
        - Attendees
        - Create
        - Attendees
        - Capabilities
        - Update
        - Except
        - Meetings
        - Meetings
        - Attendees
        - Tags
        - Transcriptions
        - Transcriptions
  /tags?operation=tag-resource:
    POST:
      summary: TagResource
      description: <p>The resource that supports tags.</p>
      tags:
        - Tags
        - Resources
        - Meetings
        - Identifiers
        - Attendees
        - Create
        - Attendees
        - Capabilities
        - Update
        - Except
        - Meetings
        - Meetings
        - Attendees
        - Tags
        - Transcriptions
        - Transcriptions
        - Tags
        - Resources
  /tags?operation=untag-resource:
    POST:
      summary: UntagResource
      description: >-
        <p>Removes the specified tags from the specified resources. When you
        specify a tag key, the action removes both that key and its associated
        value. The operation succeeds even if you attempt to remove tags from a
        resource that were already removed. Note the following:</p> <ul> <li>
        <p>To remove tags from a resource, you need the necessary permissions
        for the service that the resource belongs to as well as permissions for
        removing tags. For more information, see the documentation for the
        service whose resource you want to untag.</p> </li> <li> <p>You can only
        tag resources that are located in the specified Amazon Web Services
        Region for the calling Amazon Web Services account.</p> </li> </ul> <p>
        <b>Minimum permissions</b> </p> <p>In addition to the
        <code>tag:UntagResources</code> permission required by this operation,
        you must also have the remove tags permission defined by the service
        that created the resource. For example, to remove the tags from an
        Amazon EC2 instance using the <code>UntagResources</code> operation, you
        must have both of the following permissions:</p> <p>
        <code>tag:UntagResource</code> </p> <p>
        <code>ChimeSDKMeetings:DeleteTags</code> </p>
      tags:
        - Untag
        - Resources
        - Meetings
        - Identifiers
        - Attendees
        - Create
        - Attendees
        - Capabilities
        - Update
        - Except
        - Meetings
        - Meetings
        - Attendees
        - Tags
        - Transcriptions
        - Transcriptions
        - Tags
        - Resources
        - Tags
  /meetings/{MeetingId}/attendees/{AttendeeId}/capabilities:
    PUT:
      summary: UpdateAttendeeCapabilities
      description: >-
        <p>The capabilities that you want to update.</p> <note> <p>You use the
        capabilities with a set of values that control what the capabilities can
        do, such as <code>SendReceive</code> data. For more information about
        those values, see .</p> </note> <p>When using capabilities, be aware of
        these corner cases:</p> <ul> <li> <p>If you specify
        <code>MeetingFeatures:Video:MaxResolution:None</code> when you create a
        meeting, all API requests that include <code>SendReceive</code>,
        <code>Send</code>, or <code>Receive</code> for
        <code>AttendeeCapabilities:Video</code> will be rejected with
        <code>ValidationError 400</code>.</p> </li> <li> <p>If you specify
        <code>MeetingFeatures:Content:MaxResolution:None</code> when you create
        a meeting, all API requests that include <code>SendReceive</code>,
        <code>Send</code>, or <code>Receive</code> for
        <code>AttendeeCapabilities:Content</code> will be rejected with
        <code>ValidationError 400</code>.</p> </li> <li> <p>You can't set
        <code>content</code> capabilities to <code>SendReceive</code> or
        <code>Receive</code> unless you also set <code>video</code> capabilities
        to <code>SendReceive</code> or <code>Receive</code>. If you don't set
        the <code>video</code> capability to receive, the response will contain
        an HTTP 400 Bad Request status code. However, you can set your
        <code>video</code> capability to receive and you set your
        <code>content</code> capability to not receive.</p> </li> <li> <p>When
        you change an <code>audio</code> capability from <code>None</code> or
        <code>Receive</code> to <code>Send</code> or <code>SendReceive</code> ,
        and if the attendee left their microphone unmuted, audio will flow from
        the attendee to the other meeting participants.</p> </li> <li> <p>When
        you change a <code>video</code> or <code>content</code> capability from
        <code>None</code> or <code>Receive</code> to <code>Send</code> or
        <code>SendReceive</code> , and if the attendee turned on their video or
        content streams, remote attendees can receive those streams, but only
        after media renegotiation between the client and the Amazon Chime
        back-end server.</p> <
      tags:
        - Update
        - Attendees
        - Capabilities
        - Meetings
        - Identifiers
        - Attendees
        - Create
        - Attendees
        - Capabilities
        - Update
        - Except
        - Meetings
        - Meetings
        - Attendees
        - Tags
        - Transcriptions
        - Transcriptions
        - Tags
        - Resources
        - Tags
        - Capabilities
