openapi: 3.1.0
info:
  title: codecatalyst
paths:
  /v1/accessTokens:
    POST:
      summary: ListAccessTokens
      description: >-
        <p>Lists all personal access tokens (PATs) associated with the user who
        calls the API. You can only list PATs associated with your Amazon Web
        Services Builder ID.</p>
  /v1/spaces/{spaceName}/projects/{projectName}/devEnvironments:
    PUT:
      summary: CreateDevEnvironment
      description: >-
        <p>Creates a Dev Environment in Amazon CodeCatalyst, a cloud-based
        development environment that you can use to quickly work on the code
        stored in the source repositories of your project. </p> <note> <p>When
        created in the Amazon CodeCatalyst console, by default a Dev Environment
        is configured to have a 2 core processor, 4GB of RAM, and 16GB of
        persistent storage. None of these defaults apply to a Dev Environment
        created programmatically.</p> </note>
  /v1/spaces/{spaceName}/projects:
    POST:
      summary: ListProjects
      description: <p>Retrieves a list of projects.</p>
  /v1/spaces/{spaceName}/projects/{projectName}/sourceRepositories/{name}:
    GET:
      summary: GetSourceRepository
      description: <p>Returns information about a source repository.</p>
  /v1/spaces/{spaceName}/projects/{projectName}/sourceRepositories/{sourceRepositoryName}/branches/{name}:
    PUT:
      summary: CreateSourceRepositoryBranch
      description: >-
        <p>Creates a branch in a specified source repository in Amazon
        CodeCatalyst. </p> <note> <p>This API only creates a branch in a source
        repository hosted in Amazon CodeCatalyst. You cannot use this API to
        create a branch in a linked repository.</p> </note>
  /v1/accessTokens/{id}:
    DELETE:
      summary: DeleteAccessToken
      description: >-
        <p>Deletes a specified personal access token (PAT). A personal access
        token can only be deleted by the user who created it.</p>
  /v1/spaces/{spaceName}/projects/{projectName}/devEnvironments/{id}:
    PATCH:
      summary: UpdateDevEnvironment
      description: >-
        <p>Changes one or more values for a Dev Environment. Updating certain
        values of the Dev Environment will cause a restart.</p>
  /v1/spaces/{spaceName}/projects/{name}:
    PATCH:
      summary: UpdateProject
      description: <p>Changes one or more values for a project.</p>
  /v1/spaces/{name}:
    PATCH:
      summary: UpdateSpace
      description: <p>Changes one or more values for a space.</p>
  /v1/spaces/{spaceName}/projects/{projectName}/sourceRepositories/{sourceRepositoryName}/cloneUrls:
    GET:
      summary: GetSourceRepositoryCloneUrls
      description: >-
        <p>Returns information about the URLs that can be used with a Git client
        to clone a source repository.</p>
  /v1/spaces/{spaceName}/subscription:
    GET:
      summary: GetSubscription
      description: >-
        <p>Returns information about the Amazon Web Services account used for
        billing purposes and the billing plan for the space.</p>
  /userDetails:
    GET:
      summary: GetUserDetails
      description: <p>Returns information about a user. </p>
  /v1/spaces/{spaceName}/projects/{projectName}/workflows/{id}:
    GET:
      summary: GetWorkflow
      description: <p>Returns information about a workflow.</p>
  /v1/spaces/{spaceName}/projects/{projectName}/workflowRuns/{id}:
    GET:
      summary: GetWorkflowRun
      description: <p>Returns information about a specified run of a workflow.</p>
  /v1/spaces/{spaceName}/projects/{projectName}/devEnvironments/{devEnvironmentId}/sessions:
    POST:
      summary: ListDevEnvironmentSessions
      description: >-
        <p>Retrieves a list of active sessions for a Dev Environment in a
        project.</p>
  /v1/spaces/{spaceName}/devEnvironments:
    POST:
      summary: ListDevEnvironments
      description: <p>Retrieves a list of Dev Environments in a project.</p>
  /v1/spaces/{spaceName}/eventLogs:
    POST:
      summary: ListEventLogs
      description: >-
        <p>Retrieves a list of events that occurred during a specific time in a
        space. You can use these events to audit user and system activity in a
        space. For more information, see <a
        href="https://docs.aws.amazon.com/codecatalyst/latest/userguide/ipa-monitoring.html">Monitoring</a>
        in the <i>Amazon CodeCatalyst User Guide</i>.</p> <note>
        <p>ListEventLogs guarantees events for the last 30 days in a given
        space. You can also view and retrieve a list of management events over
        the last 90 days for Amazon CodeCatalyst in the CloudTrail console by
        viewing Event history, or by creating a trail to create and maintain a
        record of events that extends past 90 days. For more information, see <a
        href="https://docs.aws.amazon.com/awscloudtrail/latest/userguide/view-cloudtrail-events.html">Working
        with CloudTrail Event History</a> and <a
        href="https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-getting-started.html">Working
        with CloudTrail trails</a>.</p> </note>
  /v1/spaces/{spaceName}/projects/{projectName}/sourceRepositories:
    POST:
      summary: ListSourceRepositories
      description: <p>Retrieves a list of source repositories in a project.</p>
  /v1/spaces/{spaceName}/projects/{projectName}/sourceRepositories/{sourceRepositoryName}/branches:
    POST:
      summary: ListSourceRepositoryBranches
      description: <p>Retrieves a list of branches in a specified source repository.</p>
  /v1/spaces:
    POST:
      summary: ListSpaces
      description: <p>Retrieves a list of spaces.</p>
  /v1/spaces/{spaceName}/projects/{projectName}/workflowRuns:
    PUT:
      summary: StartWorkflowRun
      description: <p>Begins a run of a specified workflow.</p>
  /v1/spaces/{spaceName}/projects/{projectName}/workflows:
    POST:
      summary: ListWorkflows
      description: <p>Retrieves a list of workflows in a specified project.</p>
  /v1/spaces/{spaceName}/projects/{projectName}/devEnvironments/{id}/start:
    PUT:
      summary: StartDevEnvironment
      description: >-
        <p>Starts a specified Dev Environment and puts it into an active state.
        </p>
  /v1/spaces/{spaceName}/projects/{projectName}/devEnvironments/{id}/session:
    PUT:
      summary: StartDevEnvironmentSession
      description: <p>Starts a session for a specified Dev Environment.</p>
  /v1/spaces/{spaceName}/projects/{projectName}/devEnvironments/{id}/stop:
    PUT:
      summary: StopDevEnvironment
      description: >-
        <p>Pauses a specified Dev Environment and places it in a non-running
        state. Stopped Dev Environments do not consume compute minutes.</p>
  /v1/spaces/{spaceName}/projects/{projectName}/devEnvironments/{id}/session/{sessionId}:
    DELETE:
      summary: StopDevEnvironmentSession
      description: <p>Stops a session for a specified Dev Environment.</p>
  /session:
    GET:
      summary: VerifySession
      description: >-
        <p>Verifies whether the calling user has a valid Amazon CodeCatalyst
        login and session. If successful, this returns the ID of the user in
        Amazon CodeCatal
